const fs = require('fs');

// Fix demis
let c = fs.readFileSync('demis_new_story_tree.js', 'utf8');
c = c.replace(/''s/g, "\\'s");
c = c.replace(/'' /g, "\\' ");
c = c.replace(/didn''t/g, "didn\\'t");
c = c.replace(/hasn''t/g, "hasn\\'t");
c = c.replace(/won''t/g, "won\\'t");
c = c.replace(/can''t/g, "can\\'t");
c = c.replace(/don''t/g, "don\\'t");
c = c.replace(/isn''t/g, "isn\\'t");
c = c.replace(/wasn''t/g, "wasn\\'t");
c = c.replace(/that''s/g, "that\\'s");
c = c.replace(/it''s/g, "it\\'s");
c = c.replace(/I''m/g, "I\\'m");
c = c.replace(/you''re/g, "you\\'re");
c = c.replace(/they''re/g, "they\\'re");
c = c.replace(/we''re/g, "we\\'re");
c = c.replace(/he''s/g, "he\\'s");
c = c.replace(/she''s/g, "she\\'s");
c = c.replace(/there''s/g, "there\\'s");
c = c.replace(/here''s/g, "here\\'s");
c = c.replace(/let''s/g, "let\\'s");
c = c.replace(/what''s/g, "what\\'s");
c = c.replace(/who''s/g, "who\\'s");
fs.writeFileSync('demis_new_story_tree.js', c, 'utf8');
console.log('Fixed demis');

// Fix elon too
c = fs.readFileSync('elon_new_story_tree.js', 'utf8');
c = c.replace(/''s/g, "\\'s");
c = c.replace(/'' /g, "\\' ");
c = c.replace(/didn''t/g, "didn\\'t");
c = c.replace(/hasn''t/g, "hasn\\'t");
c = c.replace(/won''t/g, "won\\'t");
c = c.replace(/can''t/g, "can\\'t");
c = c.replace(/don''t/g, "don\\'t");
c = c.replace(/isn''t/g, "isn\\'t");
c = c.replace(/wasn''t/g, "wasn\\'t");
c = c.replace(/that''s/g, "that\\'s");
c = c.replace(/it''s/g, "it\\'s");
c = c.replace(/I''m/g, "I\\'m");
c = c.replace(/you''re/g, "you\\'re");
c = c.replace(/they''re/g, "they\\'re");
c = c.replace(/we''re/g, "we\\'re");
c = c.replace(/he''s/g, "he\\'s");
c = c.replace(/she''s/g, "she\\'s");
c = c.replace(/there''s/g, "there\\'s");
c = c.replace(/here''s/g, "here\\'s");
c = c.replace(/let''s/g, "let\\'s");
c = c.replace(/what''s/g, "what\\'s");
c = c.replace(/who''s/g, "who\\'s");
c = c.replace(/aren''t/g, "aren\\'t");
c = c.replace(/couldn''t/g, "couldn\\'t");
c = c.replace(/wouldn''t/g, "wouldn\\'t");
c = c.replace(/shouldn''t/g, "shouldn\\'t");
fs.writeFileSync('elon_new_story_tree.js', c, 'utf8');
console.log('Fixed elon');
